version: '2'
services:
    weather-app:
        image: weather
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://weather-postgresql:5432/weather
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=weather-elasticsearch:9300
        ports:
            - 8080:8080
    weather-postgresql:
        extends:
            file: postgresql.yml
            service: weather-postgresql
    weather-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: weather-elasticsearch
